server:
  port: 8899
spring:
  application:
    name: eureka-config-server
  kafka:
    bootstrap-servers: zhy.cauchy8389.com:9092
    consumer:
      group-id: groupA
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cauchy8389/J2EETest
          search-paths: config
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
