server:
  port: 10001
spring:
  kafka:
    bootstrap-servers: zhy.cauchy8389.com:9092
    consumer:
      group-id: groupA
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
  endpoint:
    bus-refresh:
      enabled: true