server:
  port: 9000
spring:
  application:
    name: eureka-zuul
  kafka:
    bootstrap-servers: zhy.cauchy8389.com:9092
  cloud:
    config:
      discovery: 
        enabled: true
        service-id: eureka-config-server
      profile: rel
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  security:
#    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

# -Dspring.cloud.bootstrap.location=D:/WorkSpace/J2EETest/src/main/resources/springcloud/config-zuul-boot.yml

