server:
  port: 9000
spring:
  application:
    name: spring-feign-invoker
  main:
      allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/