server:
  port: 8081
spring:
  application:
    name: spring-producer
  kafka:
    bootstrap-servers: 192.168.1.93:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: foo:testspringcloud.stream.producer.entity.Foo1,bar:testspringcloud.stream.producer.entity.Bar1
#事务需要开以下
#      transaction-id-prefix: tx.
#    consumer:
#      properties:
#        isolation.level: read_committed

# nohup kafka-server-start.sh config/server.properties &
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://192.168.1.50:8761/eureka/