server:
  port: 8085
spring:
  application:
    name: zk-stream-client
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: zhy.cauchy8389.com:9092
    consumer:
      group-id: groupA
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG