server:
  port: 8085
spring:
  application:
    name: zk-stream-client
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 192.168.1.51:9092
    consumer:
      group-id: operation-management-service
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.50:8761/eureka/