spring:
  application:
    name: zipkin-server
  profiles.include: shared
server:
  port: 9411  #此处没有用，必须像下面那样通过变量声明，看zipkin-server-shared文件
QUERY_PORT: 9411
HTTP_COLLECTOR_ENABLED: false
KAFKA_BOOTSTRAP_SERVERS: 192.168.1.51:9092
#KAFKA_BOOTSTRAP_SERVERS: 0.0.0.1:9092,0.0.0.2:9092,0.0.0.3:9092
#zipkin:
#  storage:
#    type: mysql
#spring:
#  datasource:
#    schema: classpath:/mysql.sql
#    url: jdbc:mysql://localhost:3306/ZIPKIN?autoReconnect=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    initialize: true
#    continueOnError: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.50:8761/eureka/